### PR TITLE
Add push_message_ru.json.js

### PR DESCRIPTION
**Pull request by kilroy98**
This file (push_message_*.json.js) support translate to other languages?

### CODE REVIEW

**Comment by paldier** [comment]
> 

Only Chinese and English.

**Comment by paldier** [comment]
https://github.com/SWRT-dev/rtax53u/blob/master/release/src/router/softcenter/dict.sh

**Comment by kilroy98** [comment]
Do I understand correctly that I need to create the string "elif ["$i" = "RU.dict" ];then" and translate all available phrases? Or did you just show the file that contains the phrases?

**Comment by paldier** [comment]
yeah, add new languages here.

**Pull request closed without merging**
